# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ShareStatusWrite(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, users: List[str]=None):  # noqa: E501
        """ShareStatusWrite - a model defined in Swagger

        :param users: The users of this ShareStatusWrite.  # noqa: E501
        :type users: List[str]
        """
        self.swagger_types = {
            'users': List[str]
        }

        self.attribute_map = {
            'users': 'users'
        }
        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'ShareStatusWrite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ShareStatus_write of this ShareStatusWrite.  # noqa: E501
        :rtype: ShareStatusWrite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[str]:
        """Gets the users of this ShareStatusWrite.

        list of user id's who can write  # noqa: E501

        :return: The users of this ShareStatusWrite.
        :rtype: List[str]
        """
        return self._users

    @users.setter
    def users(self, users: List[str]):
        """Sets the users of this ShareStatusWrite.

        list of user id's who can write  # noqa: E501

        :param users: The users of this ShareStatusWrite.
        :type users: List[str]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users
