# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ShareStatusRead(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, users: List[str]=None, public: bool=None):  # noqa: E501
        """ShareStatusRead - a model defined in Swagger

        :param users: The users of this ShareStatusRead.  # noqa: E501
        :type users: List[str]
        :param public: The public of this ShareStatusRead.  # noqa: E501
        :type public: bool
        """
        self.swagger_types = {
            'users': List[str],
            'public': bool
        }

        self.attribute_map = {
            'users': 'users',
            'public': 'public'
        }
        self._users = users
        self._public = public

    @classmethod
    def from_dict(cls, dikt) -> 'ShareStatusRead':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ShareStatus_read of this ShareStatusRead.  # noqa: E501
        :rtype: ShareStatusRead
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[str]:
        """Gets the users of this ShareStatusRead.

        list of user id's who can read  # noqa: E501

        :return: The users of this ShareStatusRead.
        :rtype: List[str]
        """
        return self._users

    @users.setter
    def users(self, users: List[str]):
        """Sets the users of this ShareStatusRead.

        list of user id's who can read  # noqa: E501

        :param users: The users of this ShareStatusRead.
        :type users: List[str]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    @property
    def public(self) -> bool:
        """Gets the public of this ShareStatusRead.

        if true, anybody can read  # noqa: E501

        :return: The public of this ShareStatusRead.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public: bool):
        """Sets the public of this ShareStatusRead.

        if true, anybody can read  # noqa: E501

        :param public: The public of this ShareStatusRead.
        :type public: bool
        """
        if public is None:
            raise ValueError("Invalid value for `public`, must not be `None`")  # noqa: E501

        self._public = public
