* vertical & horizontal scrolling is a problematic user experience
  * easily lost
  * never exactly in the right frame
  * cardinality is too high: too many wrong positions, so most of the time you are viewing something not as intented.
* map
  - https://www.researchcatalogue.net/view/486424/566538
  - https://www.researchcatalogue.net/view/81476/149707
    
* forward backward, restriciton of movement of the reader
* routes / paths / predifined frames
* navigation blocks
* background images
* https://www.researchcatalogue.net/view/55614/55626
* https://www.researchcatalogue.net/view/99519/99535

  
* An exposition is a 2dimensional sorting of Objects. It is mapping objects to a 2d space.

Most of the attempts to introduce modern technologies in the digital
presentation of visual art are based on the approach of recreating the
conventional real environment using realistically rendered two- or
three-dimensional computer models. Such forms of presentation fail to
take full advantage of the new opportunities, offered by modern
digital technologies.

One of the first to specify interactivity is Sheizaf Rafaeli. He
defines it as “an expression of the extent that in a given series of
communication exchanges, any third (or later) transmission (or
message) is related to the degree to which previous exchanges referred
to even earlier transmissions”

Ryan (2001) differentiates between internal vs. external and
exploratory vs. ontological interaction. The users are playing in
first person mode or identify themselves as an avatar in the internal
interactivity type. In the external interactivity the player has the
role of a ‘god’ in the virtual world, where he can manipulate and
change the environment. The other pair of interactivity refers to the
free ability of the user to navigate around the virtual world, while
in the exploratory form of interaction there are no changes on the
plot of the game from the user’s interaction, in contrast to the
ontological mode where the player’s decisions determine the change of
the narrative.


* expositions have a linear part and non-linear part.
* media can be searched and organised in various ways
* scalable writing, easily rewrite these things
* structure is the challange, RC should help with structuring things



* Digital obsolence book notes

Writer makes a distinction between multi media texts (Multimodal) and links to
the network of sources around a text (it's social network). I wonder if they
shouldn't be merged into one model. Should an exposition not somehow escape the notion
of just being a text with some references to other things. Is the exposition not 
a curated and annotated collection of sources ?

The task, in other words, is on some level to forget about the
arrangement of pixels on the screen and instead focus on our
experience of larger-scale structural or organizational matters.



page 101 it’s all too easy for the prob- lem of the digital future of
the book to get caught up in how the book looks rather than how it
works; in order to imagine a new digital form for the book, we need to
focus on what, and how, it communicates.

codex : (https://en.wikipedia.org/wiki/Codex) At least in the Western world, the main alternative to the paged codex
format for a long document is the continuous scroll, which was the
dominant form of document in the Ancient World. Some codices are
continuously folded like a concertina, in particular the Maya codices
and Aztec codices, which are actually long sheets of paper or animal
skin folded into pages. These do not really meet most current
definitions of the "codex" form, but are so called by convention.

These documents are, until printed, like paper under glass: mostly
unmarkable, resisting interaction with an active reader or with other
such documents in the network.

has referred to as “rear-view mirrorism,” the difficulty we have defining new technologies except in terms of older ones.

    HTML is precisely what we were trying to PREVENT— ever-breaking links, links going outward only, quotes you can't follow to their origins, no version management, no rights management.[14]

Jaron Lanier explains the difference between the World Wide Web and Nelson's vision, and the implications:

https://en.wikipedia.org/wiki/Ted_Nelson#Project_Xanadu A core
technical difference between a Nelsonian network and what we have
become familiar with online is that [Nelson's] network links were
two-way instead of one-way. In a network with two-way links, each node
knows what other nodes are linked to it. ... Two-way linking would
preserve context. It's a small simple change in how online information
should be stored that couldn't have vaster implications for culture
and the economy.[15]

*But what does this mean for structured thoughts ???*
There is nothing in an electronic book that quite corresponds to the printed table of contents. . . . In this sense, the electronic book reflects a different natural world, in which relationships are multiple and evolving: there is no great chain of being in an electronic world-book. For that very reason, an electronic book is a better analogy for contemporary views of nature, since nature today is often not regarded as a hierarchy, but rather as a network of interdependent species and systems. (Bolter 1991, 105)

But when pressed to think beyond the slowness, the small window, the pixelated fonts, what my students most often voice is their sense of disorientation, their lostness within the world of the text.

Dialog interrogate research an exposition.
An exposition should be a queriable object. 
* books are queriable by page number (usign the TOC).
* webpages can be searched, or scrolled (1d indexing)
* expositions graphical format can be scanned 2dimensionally, or navigated through the navigation map
* databases can be queried, searched, or navigated by keywords.

Test and get result !

Can we run expositions in an virtual machine. What are our technical 
for an exposition

he ends of information are always human ends, and thus the
communication of that information must always follow social purposes;
drucker 2008

Some of the metadata we need to describe our texts, after all, can be
objectively determined—author name, title of text, publisher, date—but
that information is not always imme- diately apparent, as Google
Books’ misattributed and misdated texts indicate

When research and academic libraries license electronic journals, they
do not [get] to take local possession of a copy as they did with
print. Rather, they use content stored on remote systems controlled by
publishers, and economies of scale in electronic publishing are
driving control of more and more journals into fewer and fewer
hands. Although some—but cer- tainly not all—licenses now recognize
that libraries have permanent rights to use electronic journal
content, these rights remain largely theoretical. If a publisher fails
to maintain its archive, goes out of business or, for other reasons,
stops making available the journal on which scholarship in a par-
ticular field depends, there are no practical means in place for
libraries to exercise their permanent usage rights and the scholarly
record represented by that journal would likely be lost. (Waters
2005, 1)

infrastructurally

“Organizations must secure sufficient resources to sustain their
digital preservation activities beyond the next budget cycle or the
end of a grant award” (p. 12)

// [Liyang_Yu_(auth.)]_A_Developer_s_Guide_to_the_Sem(z-lib.org).pdf

(p 11) The statements contained in different Web sites cannot be completely arbitrary. For example, they should be created by using some common terms and relation- ships, at least for a given domain. For instance, to describe a person, we have some common terms such as name, birthday and homepage, etc.

(p 11) Our agent has to be able to conduct reasoning based on its understanding of the common terms and relationships. For example, knowing the fact that resources A and B have the same e-mail address and considering the knowledge expressed by the common terms and relationships, it should be able to conclude that A and B are in fact the same resource.

(p 15) .. it would much nicer if the application could understand the meaning of the Web pages on the fly so you do not have to change your code so often.

(p 15) However, the conflict also starts from here: the current Web is entirely aimed at human readers, and it is purely display-oriented. In other words, the Web has been constructed in such a way that it is oblivious to the actual information content on any given Web site.


(p17) our Web is constructed in such a way that its documents only contain enough information for a machine to present them, not to understand them.

SPARQL query language

• RDF is a framework for representing information on the Web (RDF Concept);
• RDF is a general-purpose language for representing information in the Web

Interesting exposition by Emma Cocker: https://www.researchcatalogue.net/view/618849/618850

(RDF Syntax, RDF Schema);
• RDF is an assertional language intended to be used to express propositions using
precise formal vocabularies, particularly those specified using RDFS, for access and use over the World Wide Web, and is intended to provide a basic foundation for more advanced assertional languages with a similar purpose (RDF Semantics).

(p30) Rule #1: Knowledge (or information) is expressed as a list of statements; each statement takes the form of Subject-Predicate-Object, and this order should never be changed.

// (S)ubject (P)redicate (O)bject , SPO

especially with the development of the Linked Data project, dereferencing URIs in RDF models should return some content back, so that both human readers and applications can make use of the returned information.


(p36) Rule #2: The name of a resource must be global and should be identified by Uniform Resource Identifier (URI). The name of predicate must also be global and should be identified by URI as well.
