#+TITLE:       RC Exposition Format -- Fundamental Points (Draft)
#+AUTHOR:      Döbereiner and Schipper
#+DATE:        October/November 2019
#+OPTIONS: toc:nil        

* Introduction

An RC exposition consists of /data/, such as media objects and text,
that is structured according to an /ontology/. This structured data
object is displayed using a /renderer/ function. By following linked
data and semantic web standards, this tripartite design creates the
basis for a programmable, sustainable, editable and flexible data
architecture that can be consumed and queried by human and non-human
actors. This has important repercussions for the reading, writing and
navigation of expositions as well.

* Exposition Data Structure

** Data and Resources

The new RC exposition format centers around a workflow of data
creation, such as writing text, uploading media, representing
"real-world" events, performances, or objects as meta-data. These data
are related and contextualized in the writing process, which results
in a structured digital object, the exposition itself. Examples of
data and resources in the RC exposition format are:

- Video/image/audio files
- Text (plain text, Markdown, Microsoft Word, Open/Libre Office,
  LaTeX, html, pdf)
- Online resources, vocabularies and definitions (identified by a public URL) 
- Bibliography (BibTeX, ISBN, DOI) 
- Meta-data description of "real-world" events, objects or processes ("works")
- Scientific data 

Data objects are related in to each other according the extensible RC
exposition ontology (see section on /ontology/). All data objects
within an exposition can be searched and organized according to
categories. Objects are autonomous: Each object has a DOI and is
accessible through a unique URL that displays the object's content and
its metadata. The independence of the individual objects makes it
possible to reuse data objects in other expositions or online
publications. Copyright and licensing information is controlled on the
level of individual objects.

** Ontology 
In order to turn the exposition into a structured data object, the
possibilities of this structure need to be /modeled/. This extensible
model is to be expressed in terms of a /web ontology/ in the Web
Ontology Language (OWL)[fn:1]. Instead of limiting relations among
data to their immediate visual presentation, an exposition will be
modeled as a set of relations among distributed data. Relations
include semantic information as well as visual or temporal
properties. Following linked data principles the properties, possible
relations and types of data (and metadata) of expositions and their
components will be formally specified in terms of vocabularies and
ontologies, which will be versioned and publicly accessible. In
addition, expositions can create specific properties and relations as
supersets of the fundamental RC exposition ontology.

The RC exposition can thus be understood as a queryable data
object. Queries can refer to any specified property and their
relations. This allows for filtering, gathering and linking of
information from one or more expositions facilitating the creation of
"meta-expositions", which can be comprised of information from a
variety of sources[fn:4]. Any visual representation can be seen as a
specific query of the underlying data object.

This new level of describing and linking data must be accompanied by
the development of a publicly accessible database and a respective
API. By facilitating the updating, creation and uploading of media
entries and expositions, this API will form the foundation for
front-end editors and rendering engines but will also enable the
connection to external institutions and repositories. The "work"
feature will also be overhauled in this context and turned into a
media set and/or a resource describing a "real-world" event or object.

The formalization of the exposition format by means of OWL/RDF[fn:2]
renders relations among objects explicit and thus independent of
specific visual constraints or layouts. However, a visual layout or
proximity may itself be one of many relations among objects. Position
properties, such as "above", "to the left" etc., as well as order and
comparability, including "after", "before" and "similarity", are
examples of such relations. The specification of an RC expositions as
a set of structured relations among distributed data liberates it from
ties to specific formats (such as HTML) and thus vastly increases long
term accessibility and findability. In doing so, the RC exposition
will accommodate multiple layers of relations, such as temporal and
visual ones, that may be impossible to render
simultaneously. Moreover, it allows for validation and automatic
consistency checks.

** Renderers 
Renderers turn the data and their relations into digital media objects
for human consumption. Visual placement may be designed by the author
and/or derived from semantic information by the renderer function,
thereby translating data relations into visual or temporal structure.
While there is only one (extensible) RC ontology there can be any
number of renderers. HTML will be generated in at least two forms:
absolutely-positioned (graphical exposition) and grid-based
(responsive). Standard file formats such as PDF, SVG, EPUB etc. will
be created. These make it possible to turn a networked and distributed
exposition into a static and autonomous object, a "printed" version of
the exposition. Moreover, time-based formats and displays for visually
impaired may be generated. It is important that each format may only
render those properties and relations of the exposition that can be
displayed in its medium.

* Reading process
The reading of expositions (here understood in an extended sense) will
be transformed by enhancing navigation and exploration tools. Having
relations and properties explicitly specified allows for the
exposition to be experienced in a multiplicity of ways: It can be
searched, filtered, rearranged according to criteria, queried,
embedded and linked to external resources. New navigation tools will
be developed that extend the current outline overview and show both
visual and semantic representations of connections, paths and
groupings within the text and media data constituting the
exposition. Certain queries and paths through the data can be seen as
curated ways of exhibiting media objects.

Moreover, the reading process will more strongly affect the exposition
itself. Collective note taking and discussions relating to particular
elements of an exposition will be made possible in order develop the
specific social potential of reading digital publications.

* Writing process 
Rendering, reading and writing are deeply entangled practices in the
new RC exposition format. The construction of an exposition can start
with the author collecting data or with a visual or temporal
sketch. In the first case, the data is organized by relations which
can lead to the emergence of a visual constellation. In the second
case, the visual sketch inscribes itself into the data from which
abstractions can be derived. What follows is the translation of the
data objects and their interrelations into a structured and editable
digital object. To assist this process, the editor has various modes
to view the objects and edit the network of relations. This leads to a
workflow characterized by a permanent oscillation between modes of
rendering, editing and reading. The more metadata added by the author,
the richer the views will become in terms of structure. Examples of
editor modes include: (mind)map, lists, Graphs/trees [fn:3], text and
graphical layout.

The associated view and type of relations that are editable are
constrained by the mode of the editor.  The network of relations
between objects can also be directly edited in the textual
serialization of the format. The author can decide the degree of
mutability of the final digital object: either it is completely fixed
(the equivalent of the older graphical format), or it is left more
fluid, where the final layout may depend on the view method and
actions of the reader.


* Footnotes

[fn:4]See keyword page as an example of an exposition that draws
information from other expositions:
https://www.researchcatalogue.net/view/496747/496748

[fn:3]https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)

[fn:2]https://www.w3.org/RDF/ 

[fn:1]https://www.w3.org/OWL/ 
