# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, filename: List[str]=None):  # noqa: E501
        """Body2 - a model defined in Swagger

        :param filename: The filename of this Body2.  # noqa: E501
        :type filename: List[str]
        """
        self.swagger_types = {
            'filename': List[str]
        }

        self.attribute_map = {
            'filename': 'filename'
        }
        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_2 of this Body2.  # noqa: E501
        :rtype: Body2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filename(self) -> List[str]:
        """Gets the filename of this Body2.


        :return: The filename of this Body2.
        :rtype: List[str]
        """
        return self._filename

    @filename.setter
    def filename(self, filename: List[str]):
        """Sets the filename of this Body2.


        :param filename: The filename of this Body2.
        :type filename: List[str]
        """

        self._filename = filename
