# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DateRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start: date=None, end: date=None):  # noqa: E501
        """DateRange - a model defined in Swagger

        :param start: The start of this DateRange.  # noqa: E501
        :type start: date
        :param end: The end of this DateRange.  # noqa: E501
        :type end: date
        """
        self.swagger_types = {
            'start': date,
            'end': date
        }

        self.attribute_map = {
            'start': 'start',
            'end': 'end'
        }
        self._start = start
        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'DateRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DateRange of this DateRange.  # noqa: E501
        :rtype: DateRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self) -> date:
        """Gets the start of this DateRange.


        :return: The start of this DateRange.
        :rtype: date
        """
        return self._start

    @start.setter
    def start(self, start: date):
        """Sets the start of this DateRange.


        :param start: The start of this DateRange.
        :type start: date
        """

        self._start = start

    @property
    def end(self) -> date:
        """Gets the end of this DateRange.


        :return: The end of this DateRange.
        :rtype: date
        """
        return self._end

    @end.setter
    def end(self, end: date):
        """Sets the end of this DateRange.


        :param end: The end of this DateRange.
        :type end: date
        """

        self._end = end
