# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class License(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, external_uri: str=None, name: str=None):  # noqa: E501
        """License - a model defined in Swagger

        :param id: The id of this License.  # noqa: E501
        :type id: str
        :param external_uri: The external_uri of this License.  # noqa: E501
        :type external_uri: str
        :param name: The name of this License.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id': str,
            'external_uri': str,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'external_uri': 'externalURI',
            'name': 'name'
        }
        self._id = id
        self._external_uri = external_uri
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'License':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The License of this License.  # noqa: E501
        :rtype: License
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this License.


        :return: The id of this License.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this License.


        :param id: The id of this License.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def external_uri(self) -> str:
        """Gets the external_uri of this License.

        external definition URI.  # noqa: E501

        :return: The external_uri of this License.
        :rtype: str
        """
        return self._external_uri

    @external_uri.setter
    def external_uri(self, external_uri: str):
        """Sets the external_uri of this License.

        external definition URI.  # noqa: E501

        :param external_uri: The external_uri of this License.
        :type external_uri: str
        """
        if external_uri is None:
            raise ValueError("Invalid value for `external_uri`, must not be `None`")  # noqa: E501

        self._external_uri = external_uri

    @property
    def name(self) -> str:
        """Gets the name of this License.

        The name of the license  # noqa: E501

        :return: The name of this License.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this License.

        The name of the license  # noqa: E501

        :param name: The name of this License.
        :type name: str
        """

        self._name = name
