# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_pointer_pointer import ObjectPointerPointer  # noqa: F401,E501
from swagger_server import util


class ObjectPointer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object_type: str=None, id: str=None, pointer: ObjectPointerPointer=None):  # noqa: E501
        """ObjectPointer - a model defined in Swagger

        :param object_type: The object_type of this ObjectPointer.  # noqa: E501
        :type object_type: str
        :param id: The id of this ObjectPointer.  # noqa: E501
        :type id: str
        :param pointer: The pointer of this ObjectPointer.  # noqa: E501
        :type pointer: ObjectPointerPointer
        """
        self.swagger_types = {
            'object_type': str,
            'id': str,
            'pointer': ObjectPointerPointer
        }

        self.attribute_map = {
            'object_type': 'objectType',
            'id': 'id',
            'pointer': 'pointer'
        }
        self._object_type = object_type
        self._id = id
        self._pointer = pointer

    @classmethod
    def from_dict(cls, dikt) -> 'ObjectPointer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObjectPointer of this ObjectPointer.  # noqa: E501
        :rtype: ObjectPointer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_type(self) -> str:
        """Gets the object_type of this ObjectPointer.


        :return: The object_type of this ObjectPointer.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this ObjectPointer.


        :param object_type: The object_type of this ObjectPointer.
        :type object_type: str
        """
        allowed_values = ["mediaRecord", "exposition"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def id(self) -> str:
        """Gets the id of this ObjectPointer.

        RC id  # noqa: E501

        :return: The id of this ObjectPointer.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ObjectPointer.

        RC id  # noqa: E501

        :param id: The id of this ObjectPointer.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def pointer(self) -> ObjectPointerPointer:
        """Gets the pointer of this ObjectPointer.


        :return: The pointer of this ObjectPointer.
        :rtype: ObjectPointerPointer
        """
        return self._pointer

    @pointer.setter
    def pointer(self, pointer: ObjectPointerPointer):
        """Sets the pointer of this ObjectPointer.


        :param pointer: The pointer of this ObjectPointer.
        :type pointer: ObjectPointerPointer
        """
        if pointer is None:
            raise ValueError("Invalid value for `pointer`, must not be `None`")  # noqa: E501

        self._pointer = pointer
