# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TwoDPointer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, unit: str=None, x: float=None, y: float=None):  # noqa: E501
        """TwoDPointer - a model defined in Swagger

        :param unit: The unit of this TwoDPointer.  # noqa: E501
        :type unit: str
        :param x: The x of this TwoDPointer.  # noqa: E501
        :type x: float
        :param y: The y of this TwoDPointer.  # noqa: E501
        :type y: float
        """
        self.swagger_types = {
            'unit': str,
            'x': float,
            'y': float
        }

        self.attribute_map = {
            'unit': 'unit',
            'x': 'x',
            'y': 'y'
        }
        self._unit = unit
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'TwoDPointer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TwoDPointer of this TwoDPointer.  # noqa: E501
        :rtype: TwoDPointer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def unit(self) -> str:
        """Gets the unit of this TwoDPointer.


        :return: The unit of this TwoDPointer.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this TwoDPointer.


        :param unit: The unit of this TwoDPointer.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def x(self) -> float:
        """Gets the x of this TwoDPointer.


        :return: The x of this TwoDPointer.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this TwoDPointer.


        :param x: The x of this TwoDPointer.
        :type x: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this TwoDPointer.


        :return: The y of this TwoDPointer.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this TwoDPointer.


        :param y: The y of this TwoDPointer.
        :type y: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y
