{-
   Media Repository API
   This is the Research Catalouge Media Repository API

   The version of the OpenAPI document: 1.0.0-oas3
   Contact: support@researchcatalogue.net

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineObject1 exposing (InlineObject1, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineObject1 =
    { file : Maybe (String)
    }


decoder : Decoder InlineObject1
decoder =
    Decode.succeed InlineObject1
        |> optional "file" (Decode.nullable Decode.string) Nothing



encode : InlineObject1 -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> InlineObject1 -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : InlineObject1 -> List (String, Encode.Value)
encodePairs model =
    [ ( "file", Maybe.withDefault Encode.null (Maybe.map Encode.string model.file) )
    ]



toString : InlineObject1 -> String
toString =
    Encode.encode 0 << encode




