{-
   Media Repository API
   This is the Research Catalouge Media Repository API

   The version of the OpenAPI document: 1.0.0-oas3
   Contact: support@researchcatalogue.net

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.OpenVocabularyTerm exposing (OpenVocabularyTerm, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


{-| a term from a open vocabulary
-}
type alias OpenVocabularyTerm =
    { id : Maybe (String)
    , term : String
    }


decoder : Decoder OpenVocabularyTerm
decoder =
    Decode.succeed OpenVocabularyTerm
        |> optional "id" (Decode.nullable Decode.string) Nothing
        |> required "term" Decode.string



encode : OpenVocabularyTerm -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> OpenVocabularyTerm -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : OpenVocabularyTerm -> List (String, Encode.Value)
encodePairs model =
    [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.string model.id) )
    , ( "term", Encode.string model.term )
    ]



toString : OpenVocabularyTerm -> String
toString =
    Encode.encode 0 << encode




