{-
   Media Repository API
   This is the Research Catalouge Media Repository API

   The version of the OpenAPI document: 1.0.0-oas3
   Contact: support@researchcatalogue.net

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ShareStatusWrite exposing (ShareStatusWrite, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ShareStatusWrite =
    { users : (List String)
    }


decoder : Decoder ShareStatusWrite
decoder =
    Decode.succeed ShareStatusWrite
        |> required "users" (Decode.list Decode.string)



encode : ShareStatusWrite -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ShareStatusWrite -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ShareStatusWrite -> List (String, Encode.Value)
encodePairs model =
    [ ( "users", (Encode.list Encode.string) model.users )
    ]



toString : ShareStatusWrite -> String
toString =
    Encode.encode 0 << encode




