{-
   Media Repository API
   This is the Research Catalouge Media Repository API

   The version of the OpenAPI document: 1.0.0-oas3
   Contact: support@researchcatalogue.net

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Service exposing (getPublicMediaIndex)

import Data.MediaRecord as MediaRecord exposing (MediaRecord)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "http://localhost"


getPublicMediaIndex :
    { onSend : Result Http.Error (List MediaRecord) -> msg





    }
    -> Cmd msg
getPublicMediaIndex params =
    Http.request
        { method = "GET"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["media", "index", "public"]
            (List.filterMap identity [])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend (Decode.list MediaRecord.decoder)
        , timeout = Just 30000
        , tracker = Nothing
        }
