{-
   Media Repository API
   The Research Catalouge Media Repository API

   The version of the OpenAPI document: 1.0.0-oas3
   Contact: support@researchcatalogue.net

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Service exposing
    ( getPublicMediaIndex
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getPublicMediaIndex : Api.Request (List Api.Data.MediaRecord)
getPublicMediaIndex =
    Api.request
        "GET"
        "/media/index/public"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.mediaRecordDecoder)
